In [2]:
!pip install pymysql
!pip install pandas

import pymysql.cursors
connection = pymysql.connect(host='localhost',user='root',password= ' ' ,
                             cursorclass=pymysql.cursors.DictCursor)
import pandas as pd
import numpy as np
from datetime import date

Requirement already satisfied: pymysql in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.0.2)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas) (1.21.4)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [3]:
# function for donating-------------------------------------------------------------------------
def donate():
    
    # makes 3 arrays for each of streamer, viewer and donation tables
    strea = np.array(pd.read_sql('select * from streamer',connection))
    view = np.array(pd.read_sql('select * from viewer',connection))
    dons = np.array(pd.read_sql('select * from donation',connection))
    
    # initializes array for streamer and viewer ids
    s_ida = []
    v_ida = []
    
    # populates the arrays with the respective ids
    for d in range(len(strea)):
        s_ida.append(strea[d][0])
    for d in range(len(view)):
        v_ida.append(view[d][0])
        
    # creates new id for the new donation
    newdon_id = 200 + len(dons)
    
    # takes input of viewer id and checks if it exists in viewer ids array
    curview = int(input('input your viewer id as 1#: '))
    if curview in v_ida:
        twallet = 0  # initializes wallet value
        
        # finds wallet value and stores it
        for n in range(len(view)):
            if curview == view[n][0]: # 0th index is always the v_id
                twallet = view[n][3]  # 3rd index is always the wallet value
                

        # takes input of streamer id and checks if it exists in streamer ids array
        curstreamer = int(input('input the streamer id as #: '))
        if curstreamer in s_ida:
            
            # takes input of wanted donation
            don = int(input('input your donation amount: '))
            # stores value of difference between viewer wallet and donation and checks if its positive
            remain = twallet - don
            if (remain) > 0:
                
                for n in range(len(strea)):
                    if curstreamer==strea[n][0]:  # 0th index is always the s_id and 2nd index is donation value
                        newdon = strea[n][2] + don  # stores new streamer donation value

                        # updates streamer donation value with new donation
                        cursor.execute(f"update streamer set donations={newdon} where s_id={curstreamer}")
                        # updates viewer wallet with remaining money
                        cursor.execute(f"update viewer set wallet={remain} where v_id={curview}")
                        # creates new donation record with values
                        cursor.execute(f"insert into donation values({newdon_id},{curstreamer}," +
                                       f"{curview},{don},'{date.today()}')")
                        
                        # prints updated and new records
                        print('records updated')
                        print('\n')
                        print(pd.read_sql(f'select * from streamer where s_id={curstreamer}',connection))
                        print('\n')
                        print(pd.read_sql(f'select * from viewer where v_id={curview}',connection))
                        print('\n')
                        print(pd.read_sql(f'select * from donation where don_id={newdon_id}',connection))
                        print('\n')

            else:
                print('not enough money in wallet \n') # output if not enough money in wallet
                    
            
        else:
            print('streamer does not exist \n') # output if streamer does not exist


            
    else:
        print('viewer does not exist please register \n')  # output if viewer does not exist

        
# function for showing tables-------------------------------------------------------------------------
def showtable():
    
    print('choose a table from streamer , viewer , game , donation , stream')
    table_select = str(input('input table name: ')) # input table name
    
    # if table exists shows it using panda read_sql
    try:
        print(pd.read_sql(f'select * from {table_select}',connection))
        print('\n')
        
    except:
        print('table does not exist \n')   # ouput if table name doesnt exist
        
        
# function for showing records-------------------------------------------------------------------------
def showrecord():
    
    print('choose a table from streamer , viewer , game , donation , stream')
    table_select = str(input('input table name: ')) # input table name
    
    if table_select == 'streamer':
        # asks for streamer id input and displays record
        s_id = int(input('input streamer id as #: '))
        print(pd.read_sql(f'select * from streamer where s_id={s_id}',connection))
        print('\n')
        
    elif table_select == 'viewer':
        # asks for viewer id input and displays record
        v_id = int(input('input viewer id as 1#: '))
        print(pd.read_sql(f'select * from viewer where v_id={v_id}',connection))
        print('\n')
        
    elif table_select == 'game':
        # asks for game id input and displays record
        g_id = int(input('input game id as 1##: '))
        print(pd.read_sql(f'select * from game where g_id={g_id}',connection))
        print('\n')
        
    elif table_select == 'donation':
        # asks for donation id input and displays record
        d_id = int(input('input donation id as 2##: '))
        print(pd.read_sql(f'select * from donation where don_id={d_id}',connection))
        print('\n')
        
    elif table_select == 'stream':
        # asks for stream id input and displays record
        st_id = int(input('input stream id as 3##: '))
        print(pd.read_sql(f'select * from stream where st_id={st_id}',connection))
        print('\n')
        
    else:
        print('table does not exist \n') # ouput if table name doesnt exist


# function for adding record-------------------------------------------------------------------------
def addrecord():
    print('choose a table from streamer , viewer , game , stream')
    table_select = str(input('input table name: ')) # input table name
    
    if table_select == 'streamer':
        # inputs for record parameters
        s_id = int(input('input streamer id as #: '))
        s_name = str(input('input streamer name: '))
        s_don = int(input('input streamer donation: '))
        # inserts record in table
        cursor.execute(f"insert into streamer values({s_id},'{s_name}',{s_don},'{date.today()}')")
        print('record added')
        # prints the record
        print(pd.read_sql(f'select * from streamer where s_id={s_id}',connection))
        print('\n')
        
    elif table_select == 'viewer':
        # inputs for record parameters
        v_id = int(input('input viewer id as 1#: '))
        v_name = str(input('input viewer name: '))
        v_wal = int(input('input viewer wallet: '))
        # inserts record in table
        cursor.execute(f"insert into viewer values({v_id},'{v_name}','{date.today()}',{v_wal})")
        print('record added')
        # prints the record
        print(pd.read_sql(f'select * from viewer where v_id={v_id}',connection))
        print('\n')
        
    elif table_select == 'game':
        # inputs for record parameters
        g_id = int(input('input game id as 1##: '))
        g_name = str(input('input game name: '))
        g_dev = str(input('input game developer: '))
        # inserts record in table
        cursor.execute(f"insert into game values({g_id},'{g_name}','{g_dev}')")
        print('record added')
        # prints the record
        print(pd.read_sql(f'select * from game where g_id={g_id}',connection))
        print('\n')
        
    elif table_select == 'stream':
        # inputs for record parameters
        st_id = int(input('input stream id as 3##: '))
        s_id = int(input('input streamer id as #: '))
        g_id = int(input('input game id as 1##: '))
        # inserts record in table
        cursor.execute(f"insert into stream values({st_id},{s_id},{g_id},'{date.today()}')")
        print('record added')
        # prints the record
        print(pd.read_sql(f'select * from stream where st_id={st_id}',connection))
        print('\n')
        
    else:
        print('table does not exist \n') # ouput if table name doesnt exist
    
# function for advance mysql commands-------------------------------------------------------------------------
def advancemysql():
    inp = str(input('input mysql command: ')) # command input
    print(inp + ' \n') # prints input
    cursor.execute(inp)  # executes input
    print(cursor.fetchall()) # prints command

In [4]:
with connection.cursor() as cursor:
    # creates and uses database
    cursor.execute('drop database if exists streamio')
    cursor.execute('create database streamio')
    cursor.execute('use streamio')
    
    # creates tables
    cursor.execute('create table streamer(s_id int primary key, s_name varchar(20), donations int, join_date date)')
    cursor.execute('create table viewer(v_id int primary key, v_name varchar(20), join_date date, wallet int)')
    cursor.execute('create table game(g_id int primary key, g_name varchar(20), developer varchar(20))')
    cursor.execute('create table donation(don_id int primary key, s_id int, v_id int, price int, transaction_date '+
                   'date,foreign key(s_id) references streamer(s_id), foreign key(v_id) references viewer(v_id))')
    cursor.execute('create table stream(st_id int primary key, s_id int, g_id int, stream_date date, '+
                   'foreign key(s_id) references streamer(s_id), foreign key(g_id) references game(g_id))')
    
    # populate tables
    cursor.execute("insert into streamer values(1,'lily',0,'2010-10-05')")
    cursor.execute("insert into streamer values(2,'darko',10,'2012-07-30')")
    cursor.execute("insert into streamer values(3,'mikey',5,'2017-10-20')")
    cursor.execute("insert into streamer values(4,'dan',20,'2020-11-11')")
    cursor.execute("insert into streamer values(5,'masa',200,'2005-01-01')")
    
    cursor.execute("insert into viewer values(10,'master02','2010-05-09',30)")
    cursor.execute("insert into viewer values(11,'mikefan','2015-04-15',20)")
    cursor.execute("insert into viewer values(12,'mas5oshy','2017-05-09',5)")
    cursor.execute("insert into viewer values(13,'mark','2020-03-10',100)")
    cursor.execute("insert into viewer values(14,'darklordmaster','2022-10-26',75)")
    
    cursor.execute("insert into game values(100,'LoL','Riot Games')")
    cursor.execute("insert into game values(101,'Valorant','Riot Games')")
    cursor.execute("insert into game values(102,'Fighterz','Arcsys')")
    cursor.execute("insert into game values(103,'Hades','Supergiant')")
    
    cursor.execute("insert into donation values(200,2,12,5,'2021-10-10')")
    cursor.execute("insert into donation values(201,4,14,10,'2020-05-26')")
    cursor.execute("insert into donation values(202,5,14,5,'2020-07-20')")
    cursor.execute("insert into donation values(203,4,10,5,'2021-08-23')")
    
    cursor.execute("insert into stream values(300,1,102,'2020-01-10')")
    cursor.execute("insert into stream values(301,2,103,'2015-10-30')")
    cursor.execute("insert into stream values(302,2,101,'2021-03-31')")
    cursor.execute("insert into stream values(303,3,101,'2022-01-01')")


    
    # prints the tables
    print('   streamer')
    print(pd.read_sql('select * from streamer',connection))
    print('\n')
    print('   viewer')
    print(pd.read_sql('select * from viewer',connection))
    print('\n')
    print('   game')
    print(pd.read_sql('select * from game',connection))
    print('\n')
    print('   donation')
    print(pd.read_sql('select * from donation',connection))
    print('\n')
    print('   stream')
    print(pd.read_sql('select * from stream',connection))
    print('\n')
    
    # interface
    while True:
        try:
            # takes input to select operation
            print('select an operation: \n 1. Show table \n 2. Show record \n 3. Add record \n 4. Advanced mysql '+
                  'command \n 5. Donate to a streamer \n 6. END')
            select = int(input('input operation number: '))
            print('\n')
        
           # chooses operation based on input
            if select == 1 :
                showtable() 
            elif select == 2:
                try:
                    showrecord() 
                except: 
                    print('Error please retry \n')
            elif select == 3:
                try:
                    addrecord() 
                except: 
                    print('Error please retry \n')
            elif select == 4:
                try:
                    advancemysql() 
                except: 
                    print('invalid mysql command \n')
            elif select == 5:
                try:
                    donate() 
                except: 
                    print('Error please retry \n')
            elif select == 6: 
                # ends the operations
                print('E N D')
                break
            else:
                print("Invalid input, please input an integer from 1 to 6 \n")
        except:
            print("Invalid input, please input an integer from 1 to 6 \n")

   streamer
   s_id s_name  donations   join_date
0     1   lily          0  2010-10-05
1     2  darko         10  2012-07-30
2     3  mikey          5  2017-10-20
3     4    dan         20  2020-11-11
4     5   masa        200  2005-01-01


   viewer
   v_id          v_name   join_date  wallet
0    10        master02  2010-05-09      30
1    11         mikefan  2015-04-15      20
2    12        mas5oshy  2017-05-09       5
3    13            mark  2020-03-10     100
4    14  darklordmaster  2022-10-26      75


   game
   g_id    g_name   developer
0   100       LoL  Riot Games
1   101  Valorant  Riot Games
2   102  Fighterz      Arcsys
3   103     Hades  Supergiant


   donation
   don_id  s_id  v_id  price transaction_date
0     200     2    12      5       2021-10-10
1     201     4    14     10       2020-05-26
2     202     5    14      5       2020-07-20
3     203     4    10      5       2021-08-23


   stream
   st_id  s_id  g_id stream_date
0    300     1   102  2020-01-10
1    301     2   103  2015-10-30
2    302     2   101  2021-03-31
3    303     3   101  2022-01-01


select an operation:
 1. Show table
 2. Show record
 3. Add record
 4. Advanced mysql command
 5. Donate to a streamer
 6. END
input operation number: 6


E N D